TIMESTEP_SIMULATION_INT: int = 3600  #seconds
TIMESTEP_SIMULATION: str = f'{TIMESTEP_SIMULATION_INT}s'  #seconds
HEATING_TARGET_INDOOR_AIR_TEMP: float = 21
COOLING_TARGET_INDOOR_AIR_TEMP: float = 26
COOLING_DESIGN_AIR_TEMP: float = 100
MAX_INDOOR_AIR_TEMP: float = 26  # degree C
MIN_INDOOR_AIR_TEMP: float = 18  # degree C
