TIMESTEP_SIMULATION_INT: int = 3600  #seconds
TIMESTEP_SIMULATION: str = f'{TIMESTEP_SIMULATION_INT}s'  #seconds
TARGET_INDOOR_AIR_TEMP: float = 21
MAX_INDOOR_AIR_TEMP: float = 24  # degree C
MIN_INDOOR_AIR_TEMP: float = 18  # degree C
